name: base
channels:
  - defaults
dependencies:
  - _anaconda_depends=2020.07=py38_0
  - _ipyw_jlab_nb_ext_conf=0.1.0=py38_0
  - alabaster=0.7.12=pyhd3eb1b0_0
  - anaconda=custom=py38_1
  - anaconda-client=1.10.0=py38hecd8cb5_0
  - anaconda-navigator=2.0.3=py38_0
  - anaconda-project=0.11.0=py38hecd8cb5_0
  - anyio=3.5.0=py38hecd8cb5_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - applaunchservices=0.2.1=pyhd3eb1b0_0
  - appnope=0.1.2=py38hecd8cb5_1001
  - appscript=1.1.2=py38h9ed2024_0
  - argh=0.26.2=py38_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py38hca72f7f_0
  - asn1crypto=1.5.1=py38hecd8cb5_0
  - astroid=2.11.7=py38hecd8cb5_0
  - astropy=5.1=py38h67323c0_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - atomicwrites=1.4.0=py_0
  - attrs=21.4.0=pyhd3eb1b0_0
  - autopep8=1.5.6=pyhd3eb1b0_0
  - babel=2.9.1=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - backports=1.1=pyhd3eb1b0_0
  - backports.functools_lru_cache=1.6.4=pyhd3eb1b0_0
  - backports.shutil_get_terminal_size=1.0.0=pyhd3eb1b0_3
  - backports.tempfile=1.0=pyhd3eb1b0_1
  - backports.weakref=1.0.post1=py_1
  - beautifulsoup4=4.11.1=py38hecd8cb5_0
  - bitarray=2.5.1=py38hca72f7f_0
  - bkcharts=0.2=py38hecd8cb5_1
  - black=19.10b0=py_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - blosc=1.21.0=h8346a28_1
  - bokeh=2.4.3=py38hecd8cb5_0
  - boto=2.49.0=py38_0
  - bottleneck=1.3.5=py38h67323c0_0
  - brotli=1.0.9=hb1e8313_2
  - brotlipy=0.7.0=py38h9ed2024_1003
  - bzip2=1.0.8=h1de35cc_0
  - c-ares=1.18.1=hca72f7f_0
  - ca-certificates=2022.07.19=hecd8cb5_0
  - certifi=2022.6.15=py38hecd8cb5_0
  - cffi=1.15.0=py38hc55c11b_1
  - chardet=4.0.0=py38hecd8cb5_1003
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py38hecd8cb5_0
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - clyent=1.2.2=py38_1
  - colorama=0.4.5=py38hecd8cb5_0
  - conda=4.13.0=py38hecd8cb5_0
  - conda-build=3.21.9=py38hecd8cb5_0
  - conda-content-trust=0.1.3=py38hecd8cb5_0
  - conda-env=2.6.0=1
  - conda-pack=0.6.0=pyhd3eb1b0_0
  - conda-package-handling=1.8.1=py38hca72f7f_0
  - conda-repo-cli=1.0.5=py38hecd8cb5_0
  - conda-token=0.3.0=pyhd3eb1b0_0
  - conda-verify=3.4.2=py_1
  - contextlib2=0.6.0.post1=pyhd3eb1b0_0
  - cryptography=37.0.1=py38hf6deb26_0
  - curl=7.84.0=hca72f7f_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cython=0.29.30=py38he9d5cce_0
  - cytoolz=0.11.0=py38haf1e3a3_0
  - dask=2022.7.0=py38hecd8cb5_0
  - dask-core=2022.7.0=py38hecd8cb5_0
  - dataclasses=0.8=pyh6d0b6a4_7
  - dbus=1.13.18=h18a8e69_0
  - debugpy=1.5.1=py38he9d5cce_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - diff-match-patch=20200713=pyhd3eb1b0_0
  - dill=0.3.4=pyhd3eb1b0_0
  - distributed=2022.7.0=py38hecd8cb5_0
  - docutils=0.18.1=py38hecd8cb5_3
  - entrypoints=0.4=py38hecd8cb5_0
  - et_xmlfile=1.1.0=py38hecd8cb5_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.4.4=he9d5cce_0
  - fastcache=1.1.0=py38h1de35cc_0
  - filelock=3.6.0=pyhd3eb1b0_0
  - flake8=3.9.0=pyhd3eb1b0_0
  - flask=1.1.2=pyhd3eb1b0_0
  - freetype=2.11.0=hd8bbffd_0
  - fsspec=2022.3.0=py38hecd8cb5_0
  - future=0.18.2=py38_1
  - get_terminal_size=1.0.0=h7520d66_0
  - gettext=0.21.0=h7535e17_0
  - gevent=21.8.0=py38h9ed2024_1
  - giflib=5.2.1=haf1e3a3_0
  - glib=2.69.1=h8346a28_1
  - glob2=0.7=pyhd3eb1b0_0
  - gmp=6.2.1=he9d5cce_3
  - gmpy2=2.1.2=py38hd5de756_0
  - greenlet=1.1.1=py38h23ab428_0
  - h5py=2.10.0=py38h3134771_0
  - hdf5=1.10.4=hfa1e0ec_0
  - heapdict=1.0.1=pyhd3eb1b0_0
  - html5lib=1.1=pyhd3eb1b0_0
  - icu=58.2=h0a44026_3
  - idna=3.3=pyhd3eb1b0_0
  - imageio=2.19.3=py38hecd8cb5_0
  - imagesize=1.4.1=py38hecd8cb5_0
  - importlib-metadata=4.11.3=py38hecd8cb5_0
  - importlib_metadata=4.11.3=hd3eb1b0_0
  - importlib_resources=5.2.0=pyhd3eb1b0_1
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intel-openmp=2021.4.0=hecd8cb5_3538
  - intervaltree=3.1.0=pyhd3eb1b0_0
  - ipykernel=6.9.1=py38hecd8cb5_0
  - ipython=8.4.0=py38hecd8cb5_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - isort=5.9.3=pyhd3eb1b0_0
  - itsdangerous=2.0.1=pyhd3eb1b0_0
  - jbig=2.1=h4d881f8_0
  - jdcal=1.4.1=pyhd3eb1b0_0
  - jedi=0.17.2=py38hecd8cb5_1
  - jinja2=2.11.3=pyhd3eb1b0_0
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9e=hca72f7f_0
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.4.0=py38hecd8cb5_0
  - jupyter=1.0.0=py38hecd8cb5_8
  - jupyter_client=7.2.2=py38hecd8cb5_0
  - jupyter_console=6.4.3=pyhd3eb1b0_0
  - jupyter_core=4.10.0=py38hecd8cb5_0
  - jupyter_server=1.18.1=py38hecd8cb5_0
  - jupyterlab=3.4.4=py38hecd8cb5_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.10.3=pyhd3eb1b0_1
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - keyring=23.4.0=py38hecd8cb5_0
  - kiwisolver=1.4.2=py38he9d5cce_0
  - krb5=1.19.2=hcd88c3b_0
  - lazy-object-proxy=1.6.0=py38h9ed2024_0
  - lcms2=2.12=hf1fd2bf_0
  - libarchive=3.5.2=ha0e9c3a_0
  - libcryptominisat=5.6.6=hf1b45e0_0
  - libcurl=7.84.0=h6dfd666_0
  - libcxx=12.0.0=h2f01273_0
  - libedit=3.1.20210910=hca72f7f_0
  - libev=4.33=h9ed2024_1
  - libffi=3.3=hb1e8313_2
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.16=hca72f7f_2
  - liblief=0.11.5=he9d5cce_1
  - libllvm11=11.1.0=h46f1229_1
  - libllvm9=9.0.1=h21ff451_1
  - libnghttp2=1.46.0=ha29bfda_0
  - libpng=1.6.37=ha441bb4_0
  - libsodium=1.0.18=h1de35cc_0
  - libspatialindex=1.9.3=h23ab428_0
  - libssh2=1.10.0=h0a4fc7d_0
  - libtiff=4.2.0=hdb42f99_1
  - libuv=1.40.0=haf1e3a3_0
  - libwebp=1.2.2=h56c3ce4_0
  - libwebp-base=1.2.2=hca72f7f_0
  - libxml2=2.9.14=hbf8cd5e_0
  - libxslt=1.1.35=h5b33f42_0
  - llvm-openmp=12.0.0=h0dcd299_1
  - llvmlite=0.38.0=py38h8346a28_0
  - locket=1.0.0=py38hecd8cb5_0
  - lxml=4.9.1=py38h65b224f_0
  - lz4=3.1.3=py38h9ed2024_0
  - lz4-c=1.9.3=h23ab428_1
  - lzo=2.10=haf1e3a3_2
  - markupsafe=2.0.1=py38h9ed2024_0
  - matplotlib-base=3.5.1=py38hfb0c5b7_1
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mccabe=0.6.1=py38_1
  - mistune=0.8.4=py38h1de35cc_1001
  - mkl=2021.4.0=hecd8cb5_637
  - mkl-service=2.4.0=py38h9ed2024_0
  - mkl_fft=1.3.1=py38h4ab4a9b_0
  - mkl_random=1.2.2=py38hb2f4e1b_0
  - mock=4.0.3=pyhd3eb1b0_0
  - more-itertools=8.12.0=pyhd3eb1b0_0
  - mpc=1.1.0=h6ef4df4_1
  - mpfr=4.0.2=h9066e36_1
  - mpmath=1.2.1=py38hecd8cb5_0
  - msgpack-python=1.0.3=py38haf03e11_0
  - multipledispatch=0.6.0=py38_0
  - munkres=1.1.4=py_0
  - mypy_extensions=0.4.3=py38hecd8cb5_1
  - navigator-updater=0.2.1=py38_0
  - nbclassic=0.3.5=pyhd3eb1b0_0
  - nbclient=0.5.13=py38hecd8cb5_0
  - nbconvert=6.4.4=py38hecd8cb5_0
  - nbformat=5.3.0=py38hecd8cb5_0
  - ncurses=6.3=hca72f7f_3
  - nest-asyncio=1.5.5=py38hecd8cb5_0
  - networkx=2.8.4=py38hecd8cb5_0
  - nltk=3.7=pyhd3eb1b0_0
  - nose=1.3.7=pyhd3eb1b0_1008
  - notebook=6.4.12=py38hecd8cb5_0
  - numba=0.55.1=py38hae1ba45_0
  - numexpr=2.8.3=py38h2e5f0a9_0
  - numpy=1.21.5=py38h2e5f0a9_3
  - numpy-base=1.21.5=py38h3b1a694_3
  - numpydoc=1.4.0=py38hecd8cb5_0
  - olefile=0.46=pyhd3eb1b0_0
  - openpyxl=3.0.10=py38hca72f7f_0
  - openssl=1.1.1q=hca72f7f_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.4.3=py38he9d5cce_0
  - pandoc=2.12=hecd8cb5_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.7.0=py_0
  - partd=1.2.0=pyhd3eb1b0_1
  - path=16.2.0=pyhd3eb1b0_0
  - path.py=12.5.0=hd3eb1b0_0
  - pathlib=1.0.1=py38_2
  - pathlib2=2.3.6=py38hecd8cb5_2
  - pathspec=0.7.0=py_0
  - pathtools=0.1.2=pyhd3eb1b0_1
  - patsy=0.5.2=py38hecd8cb5_1
  - pcre=8.45=h23ab428_0
  - pep8=1.7.1=py38hecd8cb5_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.2.0=py38hde71d04_1
  - pip=22.1.2=py38hecd8cb5_0
  - pkginfo=1.8.2=pyhd3eb1b0_0
  - platformdirs=2.4.0=pyhd3eb1b0_0
  - pluggy=1.0.0=py38hecd8cb5_1
  - ply=3.11=py38_0
  - prometheus_client=0.14.1=py38hecd8cb5_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - prompt_toolkit=3.0.20=hd3eb1b0_0
  - psutil=5.9.0=py38hca72f7f_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py=1.11.0=pyhd3eb1b0_0
  - py-lief=0.11.5=py38he9d5cce_1
  - pycodestyle=2.6.0=pyhd3eb1b0_0
  - pycosat=0.6.3=py38h1de35cc_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pycryptosat=5.6.6=py38hf1b45e0_0
  - pycurl=7.45.1=py38h0a4fc7d_0
  - pydocstyle=6.1.1=pyhd3eb1b0_0
  - pyerfa=2.0.0=py38h9ed2024_0
  - pyflakes=2.2.0=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pylint=2.14.5=py38hecd8cb5_0
  - pyls-black=0.4.6=hd3eb1b0_0
  - pyls-spyder=0.3.2=pyhd3eb1b0_0
  - pyodbc=4.0.32=py38he9d5cce_1
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyqt=5.9.2=py38h655552a_2
  - pyrsistent=0.18.0=py38hca72f7f_0
  - pysocks=1.7.1=py38_1
  - pytables=3.6.1=py38h4727e94_0
  - pytest=7.1.2=py38hecd8cb5_0
  - python=3.8.8=h88f2d9e_5
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.15.1=pyhd3eb1b0_0
  - python-jsonrpc-server=0.4.0=py_0
  - python-language-server=0.36.2=pyhd3eb1b0_0
  - python-libarchive-c=2.9=pyhd3eb1b0_1
  - python.app=3=py38h9ed2024_0
  - pytz=2022.1=py38hecd8cb5_0
  - pywavelets=1.3.0=py38hca72f7f_0
  - pyyaml=6.0=py38hca72f7f_1
  - pyzmq=23.2.0=py38he9d5cce_0
  - qdarkstyle=2.8.1=py_0
  - qt=5.9.7=h468cd18_1
  - qtawesome=1.0.3=pyhd3eb1b0_0
  - qtconsole=5.3.1=py38hecd8cb5_0
  - qtpy=2.0.1=pyhd3eb1b0_0
  - readline=8.1.2=hca72f7f_1
  - requests=2.28.1=py38hecd8cb5_0
  - ripgrep=12.1.1=0
  - rope=0.22.0=pyhd3eb1b0_0
  - rtree=0.9.7=py38hecd8cb5_1
  - ruamel_yaml=0.15.100=py38h9ed2024_0
  - scikit-image=0.19.2=py38hae1ba45_0
  - scikit-learn=1.1.1=py38he9d5cce_0
  - scipy=1.7.3=py38h8c7af03_0
  - seaborn=0.11.2=pyhd3eb1b0_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=61.2.0=py38hecd8cb5_0
  - simplegeneric=0.8.1=py38_2
  - singledispatch=3.7.0=pyhd3eb1b0_1001
  - sip=4.19.8=py38h0a44026_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.9=he9d5cce_0
  - sniffio=1.2.0=py38hecd8cb5_1
  - snowballstemmer=2.2.0=pyhd3eb1b0_0
  - sortedcollections=2.1.0=pyhd3eb1b0_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.3.1=pyhd3eb1b0_0
  - sphinx=5.0.2=py38hecd8cb5_0
  - sphinxcontrib=1.0=py38_1
  - sphinxcontrib-applehelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-devhelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd3eb1b0_0
  - sphinxcontrib-websupport=1.2.4=py_0
  - spyder=4.2.5=py38hecd8cb5_0
  - spyder-kernels=1.10.2=py38hecd8cb5_0
  - sqlalchemy=1.4.39=py38hca72f7f_0
  - sqlite=3.39.0=h707629a_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - statsmodels=0.13.2=py38hca72f7f_0
  - sympy=1.10.1=py38hecd8cb5_0
  - tbb=2021.5.0=haf03e11_0
  - tblib=1.7.0=pyhd3eb1b0_0
  - terminado=0.13.1=py38hecd8cb5_0
  - testpath=0.6.0=py38hecd8cb5_0
  - textdistance=4.2.1=pyhd3eb1b0_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - three-merge=0.1.1=pyhd3eb1b0_0
  - tifffile=2020.10.1=py38h0cf3a3e_2
  - tk=8.6.12=h5d9f67b_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.0.1=py38hecd8cb5_0
  - tomlkit=0.11.1=py38hecd8cb5_0
  - toolz=0.11.2=pyhd3eb1b0_0
  - tornado=6.1=py38h9ed2024_0
  - tqdm=4.64.0=py38hecd8cb5_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typed-ast=1.4.3=py38h9ed2024_1
  - ujson=5.4.0=py38he9d5cce_0
  - unicodecsv=0.14.1=py38_0
  - unixodbc=2.3.9=haf1e3a3_0
  - urllib3=1.26.11=py38hecd8cb5_0
  - watchdog=1.0.2=py38h9ed2024_1
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py38_1
  - websocket-client=0.58.0=py38hecd8cb5_4
  - werkzeug=2.0.3=pyhd3eb1b0_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - widgetsnbextension=3.5.2=py38hecd8cb5_0
  - wrapt=1.14.1=py38hca72f7f_0
  - wurlitzer=3.0.2=py38hecd8cb5_0
  - xlrd=2.0.1=pyhd3eb1b0_0
  - xlsxwriter=3.0.3=pyhd3eb1b0_0
  - xlwings=0.24.9=py38hecd8cb5_0
  - xlwt=1.3.0=py38_0
  - xmltodict=0.12.0=pyhd3eb1b0_0
  - xz=5.2.5=hca72f7f_1
  - yaml=0.2.5=haf1e3a3_0
  - yapf=0.31.0=pyhd3eb1b0_0
  - zeromq=4.3.4=h23ab428_0
  - zict=2.1.0=py38hecd8cb5_0
  - zipp=3.8.0=py38hecd8cb5_0
  - zlib=1.2.12=h4dc903c_2
  - zope=1.0=py38_1
  - zope.event=4.5.0=py38_0
  - zope.interface=5.4.0=py38h9ed2024_0
  - zstd=1.5.2=hcb37349_0
  - pip:
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - altair==4.2.0
    - analytics-python==1.4.0
    - async-timeout==4.0.2
    - avro==1.10.2
    - backoff==1.10.0
    - backports-zoneinfo==0.2.1
    - bcrypt==3.2.2
    - boto3==1.24.12
    - botocore==1.27.12
    - confluent-kafka==1.8.2
    - dateparser==1.1.1
    - docker-pycreds==0.4.0
    - faker==13.3.4
    - fastapi==0.79.0
    - fastavro==1.4.11
    - ffmpy==0.3.0
    - fonttools==4.33.3
    - frozenlist==1.3.0
    - furl==2.1.3
    - gitdb==4.0.9
    - gitpython==3.1.27
    - gradio==3.1.0
    - great-expectations==0.14.3
    - h11==0.12.0
    - hopsworks==3.0.1
    - hsfs==3.0.0
    - hsml==3.0.0
    - httpcore==0.15.0
    - httpx==0.23.0
    - javaobj-py3==0.4.3
    - jmespath==1.0.1
    - jsonpatch==1.32
    - jsonpointer==2.3
    - linkify-it-py==1.0.3
    - markdown-it-py==2.1.0
    - matplotlib==3.5.2
    - mdit-py-plugins==0.3.0
    - mdurl==0.1.1
    - monotonic==1.6
    - multidict==6.0.2
    - oauthlib==3.2.0
    - orderedmultidict==1.0.1
    - orjson==3.7.8
    - paramiko==2.11.0
    - promise==2.3
    - protobuf==3.20.1
    - pyarrow==8.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycryptodome==3.15.0
    - pycryptodomex==3.14.1
    - pydantic==1.9.1
    - pydub==0.25.1
    - pyhopshive==0.6.4.1.dev0
    - pyhumps==1.6.1
    - pyjks==20.0.0
    - pymysql==1.0.2
    - pynacl==1.5.0
    - pyparsing==2.4.7
    - python-dotenv==0.20.0
    - python-multipart==0.0.5
    - pytz-deprecation-shim==0.1.0.post0
    - regex==2022.3.2
    - requests-oauthlib==1.3.1
    - rfc3986==1.5.0
    - ruamel-yaml==0.17.17
    - ruamel-yaml-clib==0.2.6
    - s3transfer==0.6.0
    - sentry-sdk==1.9.0
    - service-identity==21.1.0
    - setproctitle==1.3.0
    - shortuuid==1.0.9
    - smmap==5.0.0
    - starlette==0.19.1
    - termcolor==1.1.0
    - textblob==0.17.1
    - thrift==0.16.0
    - tweepy==4.10.0
    - twofish==0.3.0
    - typing-extensions==4.3.0
    - tzdata==2022.1
    - tzlocal==4.2
    - uc-micro-py==1.0.1
    - unicorn-binance-rest-api==1.5.0
    - uvicorn==0.18.2
    - vadersentiment==3.3.2
    - wandb==0.12.21
    - yarl==1.7.2
prefix: /Users/davitbzhalava/opt/anaconda3
