wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.0
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.0
    start_time: 1659645115.21659
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 13
      - 23
      4: 3.8.0
      5: 0.13.0
      8:
      - 1
      - 3
      - 5
