wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1659606345
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 16
      4: 3.8.13
      5: 0.12.21
      8:
      - 1
      - 5
      10:
      - 5
    viz:
      calibration_curve:
        historyFieldSettings:
          key: calibration_curve
          x-axis: _step
        id: wandb/calibration/v1
      class_proportions:
        historyFieldSettings:
          key: class_proportions
          x-axis: _step
        id: wandb/class_proportions/v1
      confusion_matrix:
        historyFieldSettings:
          key: confusion_matrix
          x-axis: _step
        id: wandb/confusion_matrix/v1
      feature_importances:
        historyFieldSettings:
          key: feature_importances
          x-axis: _step
        id: wandb/feature_importances/v1
      precision_recall:
        historyFieldSettings:
          key: precision_recall
          x-axis: _step
        id: wandb/pr_curve/v1
      roc:
        historyFieldSettings:
          key: roc
          x-axis: _step
        id: wandb/roc/v1
      summary_metrics:
        historyFieldSettings:
          key: summary_metrics
          x-axis: _step
        id: wandb/metrics/v1
criterion:
  desc: null
  value: gini
min_samples_split:
  desc: null
  value: 15
n_estimators:
  desc: null
  value: 75
